[package]
name = "cayenchat-irc-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
irc.workspace = true
rustls.workspace = true
encoding.workspace = true
tokio.workspace = true
futures-util.workspace = true
base64.workspace = true
